spring:
  batch:
    job:
      # 默认自动执行定义的Job(true)，改为false，需要jobLaucher.run执行
      enabled: false
  datasource:
    # 数据库连接池类型
    type: com.zaxxer.hikari.HikariDataSource
    # 使用MySQL数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MySQL数据库连接URL
    url: jdbc:mysql://106.13.224.xxx:3306/cxf-daybat?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true&useSSL=false
    # oracle数据库连接URL
    #url: jdbc:oracle:thin:@localhost:1521:ycorcl
    # 数据库连接用户名
    username: yourname
    # 数据库连接密码
    password: yourpassword
    hikari:
      # 客户端等待连接池连接的最大毫秒数
      connection-timeout: 30000
      # 空闲时最小连接数-
      minimum-idle: 10
      # 连接池最大连接数
      maximum-pool-size: 200
      # 是允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 60000
      # 池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 600000
      # 配置从池返回的连接的默认自动提交行为。默认值为true。
      auto-commit: true
      # 连接池的名称
      pool-name: daybatHikariCP
      # 开启连接监测泄露
      leak-detection-threshold: 5000
      # 测试连接数据库
      connection-test-query: SELECT 1
      data-source-properties:
        # 是否启用Prep缓存
        cachePrepStmts: true
        # Prep缓存大小
        prepStmtCacheSize: 250
        # Prep缓存sql限制大小
        prepStmtCacheSqlLimit: 2048
        # 是否用服务缓存Prep
        useServerPrepStmts: true